/*******************************************************************************
* File Name: cyfitter_gpio.h
* 
* PSoC Creator  4.4
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_GPIO_H
#define INCLUDED_CYFITTER_GPIO_H
#include "cy_device_headers.h"

/* pLed1 */
#define pLed1_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define pLed1_0_INBUF_ENABLED 0u
#define pLed1_0_INIT_DRIVESTATE 0u
#define pLed1_0_INIT_MUXSEL 0u
#define pLed1_0_INPUT_SYNC 2u
#define pLed1_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define pLed1_0_NUM 0u
#define pLed1_0_PORT GPIO_PRT9
#define pLed1_0_SLEWRATE CY_GPIO_SLEW_FAST
#define pLed1_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define pLed1_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define pLed1_INBUF_ENABLED 0u
#define pLed1_INIT_DRIVESTATE 0u
#define pLed1_INIT_MUXSEL 0u
#define pLed1_INPUT_SYNC 2u
#define pLed1_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define pLed1_NUM 0u
#define pLed1_PORT GPIO_PRT9
#define pLed1_SLEWRATE CY_GPIO_SLEW_FAST
#define pLed1_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* pLed2 */
#define pLed2_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define pLed2_0_INBUF_ENABLED 0u
#define pLed2_0_INIT_DRIVESTATE 0u
#define pLed2_0_INIT_MUXSEL 0u
#define pLed2_0_INPUT_SYNC 2u
#define pLed2_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define pLed2_0_NUM 1u
#define pLed2_0_PORT GPIO_PRT9
#define pLed2_0_SLEWRATE CY_GPIO_SLEW_FAST
#define pLed2_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define pLed2_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define pLed2_INBUF_ENABLED 0u
#define pLed2_INIT_DRIVESTATE 0u
#define pLed2_INIT_MUXSEL 0u
#define pLed2_INPUT_SYNC 2u
#define pLed2_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define pLed2_NUM 1u
#define pLed2_PORT GPIO_PRT9
#define pLed2_SLEWRATE CY_GPIO_SLEW_FAST
#define pLed2_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

#endif /* INCLUDED_CYFITTER_GPIO_H */
